### ISSUE TITLE
Incompatible with `androidx.compose.material3:material3:1.3.0`

### ISSUE THREAD

**Issue by pewaru-333** [zhanghai/ComposePreference#8]
## Expected Behavior
Working normally

## Actual Behavior
```
java.lang.NoSuchMethodError: 
No static method AlertDialog(Lkotlin/jvm/functions/Function0;Landroidx/compose/ui/Modifier;Landroidx/compose/ui/window/DialogProperties;Lkotlin/jvm/functions/Function2;Landroidx/compose/runtime/Composer;II)V in class
Landroidx/compose/material3/AndroidAlertDialog_androidKt; or its super classes (declaration of 'androidx.compose.material3.AndroidAlertDialog_androidKt' appears in ... ) 
at me.zhanghai.compose.preference.PreferenceAlertDialogKt.PreferenceAlertDialog(PreferenceAlertDialog.kt:51)	
at me.zhanghai.compose.preference.ListPreferenceKt.ListPreference(ListPreference.kt:148) 
at me.zhanghai.compose.preference.ListPreferenceKt$ListPreference$14.invoke(Unknown Source:42) 
at me.zhanghai.compose.preference.ListPreferenceKt$ListPreference$14.invoke(Unknown Source:10) ...
```

## Steps to Reproduce the Problem

1. Update androidx.compose.material3:material3 from 1.2.1 to 1.3.0

**Comment by zhanghai** [comment]
Fixed in v1.1.0.
